"""Initial schema with manga, library, chapters, metadata_cache, downloads

Revision ID: 2cb161deac7a
Revises: 
Create Date: 2026-01-02 03:40:30.905028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb161deac7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('source_manga_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=True),
    sa.Column('shikimori_id', sa.Integer(), nullable=True),
    sa.Column('mangaupdates_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_english', sa.String(length=500), nullable=True),
    sa.Column('title_romaji', sa.String(length=500), nullable=True),
    sa.Column('title_native', sa.String(length=500), nullable=True),
    sa.Column('alt_titles', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('releasing', 'finished', 'hiatus', 'cancelled', 'not_yet_released', name='manga_status'), nullable=True),
    sa.Column('manga_type', sa.String(length=50), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('demographics', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_anilist', sa.Float(), nullable=True),
    sa.Column('rating_mal', sa.Float(), nullable=True),
    sa.Column('rating_kitsu', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('cover_image_large', sa.String(length=1000), nullable=True),
    sa.Column('cover_image_medium', sa.String(length=1000), nullable=True),
    sa.Column('banner_image', sa.String(length=1000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_metadata_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('is_licensed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_manga_id', name='uq_manga_source_id')
    )
    op.create_index(op.f('ix_manga_anilist_id'), 'manga', ['anilist_id'], unique=False)
    op.create_index(op.f('ix_manga_kitsu_id'), 'manga', ['kitsu_id'], unique=False)
    op.create_index(op.f('ix_manga_mal_id'), 'manga', ['mal_id'], unique=False)
    op.create_index(op.f('ix_manga_mangaupdates_id'), 'manga', ['mangaupdates_id'], unique=False)
    op.create_index('ix_manga_rating_popularity', 'manga', ['rating_average', 'popularity_score'], unique=False)
    op.create_index(op.f('ix_manga_shikimori_id'), 'manga', ['shikimori_id'], unique=False)
    op.create_index(op.f('ix_manga_source_id'), 'manga', ['source_id'], unique=False)
    op.create_index(op.f('ix_manga_source_manga_id'), 'manga', ['source_manga_id'], unique=False)
    op.create_index(op.f('ix_manga_title'), 'manga', ['title'], unique=False)
    op.create_index('ix_manga_title_status', 'manga', ['title', 'status'], unique=False)
    op.create_index(op.f('ix_manga_year'), 'manga', ['year'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manga_id', sa.UUID(), nullable=False),
    sa.Column('source_chapter_id', sa.String(length=255), nullable=False),
    sa.Column('chapter_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('scanlator', sa.String(length=255), nullable=True),
    sa.Column('groups', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pages_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manga_id', 'source_chapter_id', 'language', name='uq_chapter_manga_source_lang')
    )
    op.create_index('ix_chapter_number_lang', 'chapters', ['chapter_number', 'language'], unique=False)
    op.create_index(op.f('ix_chapters_cached_at'), 'chapters', ['cached_at'], unique=False)
    op.create_index(op.f('ix_chapters_chapter_number'), 'chapters', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_chapters_language'), 'chapters', ['language'], unique=False)
    op.create_index(op.f('ix_chapters_manga_id'), 'chapters', ['manga_id'], unique=False)
    op.create_index(op.f('ix_chapters_source_chapter_id'), 'chapters', ['source_chapter_id'], unique=False)
    op.create_table('library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manga_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('reading', 'completed', 'plan_to_read', 'dropped', 'on_hold', name='reading_status'), nullable=False),
    sa.Column('last_chapter_read', sa.String(length=50), nullable=True),
    sa.Column('last_chapter_id', sa.String(length=255), nullable=True),
    sa.Column('last_page_read', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_added_at'), 'library', ['added_at'], unique=False)
    op.create_index(op.f('ix_library_manga_id'), 'library', ['manga_id'], unique=False)
    op.create_index(op.f('ix_library_status'), 'library', ['status'], unique=False)
    op.create_table('metadata_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manga_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('cache_type', sa.String(length=50), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'cache_key', 'cache_type', name='uq_cache_provider_key_type')
    )
    op.create_index('ix_cache_expires', 'metadata_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_metadata_cache_cache_key'), 'metadata_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_metadata_cache_expires_at'), 'metadata_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_metadata_cache_manga_id'), 'metadata_cache', ['manga_id'], unique=False)
    op.create_index(op.f('ix_metadata_cache_provider'), 'metadata_cache', ['provider'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('downloading', 'completed', 'failed', 'deleted', name='download_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index('ix_download_status_downloaded', 'downloads', ['status', 'downloaded_at'], unique=False)
    op.create_index(op.f('ix_downloads_chapter_id'), 'downloads', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_downloads_downloaded_at'), 'downloads', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_downloaded_at'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_chapter_id'), table_name='downloads')
    op.drop_index('ix_download_status_downloaded', table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_metadata_cache_provider'), table_name='metadata_cache')
    op.drop_index(op.f('ix_metadata_cache_manga_id'), table_name='metadata_cache')
    op.drop_index(op.f('ix_metadata_cache_expires_at'), table_name='metadata_cache')
    op.drop_index(op.f('ix_metadata_cache_cache_key'), table_name='metadata_cache')
    op.drop_index('ix_cache_expires', table_name='metadata_cache')
    op.drop_table('metadata_cache')
    op.drop_index(op.f('ix_library_status'), table_name='library')
    op.drop_index(op.f('ix_library_manga_id'), table_name='library')
    op.drop_index(op.f('ix_library_added_at'), table_name='library')
    op.drop_table('library')
    op.drop_index(op.f('ix_chapters_source_chapter_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_manga_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_language'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_number'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_cached_at'), table_name='chapters')
    op.drop_index('ix_chapter_number_lang', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_manga_year'), table_name='manga')
    op.drop_index('ix_manga_title_status', table_name='manga')
    op.drop_index(op.f('ix_manga_title'), table_name='manga')
    op.drop_index(op.f('ix_manga_source_manga_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_source_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_shikimori_id'), table_name='manga')
    op.drop_index('ix_manga_rating_popularity', table_name='manga')
    op.drop_index(op.f('ix_manga_mangaupdates_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_mal_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_kitsu_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_anilist_id'), table_name='manga')
    op.drop_table('manga')
    # ### end Alembic commands ###
