"""Add normalized metadata tables (genres, tags, people, ratings, images)

Revision ID: 8e6ff8901f1e
Revises: 2cb161deac7a
Create Date: 2026-01-06 19:33:13.261757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e6ff8901f1e'
down_revision: Union[str, Sequence[str], None] = '2cb161deac7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_native', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'name_native', name='uq_person_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('external_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_links_manga_id'), 'external_links', ['manga_id'], unique=False)
    op.create_table('manga_genres',
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manga_id', 'genre_id')
    )
    op.create_table('manga_images',
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cover_extra_large', sa.String(length=1000), nullable=True),
    sa.Column('cover_large', sa.String(length=1000), nullable=True),
    sa.Column('cover_medium', sa.String(length=1000), nullable=True),
    sa.Column('banner_image', sa.String(length=1000), nullable=True),
    sa.Column('dominant_color', sa.String(length=7), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manga_id')
    )
    op.create_table('manga_ratings',
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rating_anilist', sa.Float(), nullable=True),
    sa.Column('rating_mal', sa.Float(), nullable=True),
    sa.Column('rating_kitsu', sa.Float(), nullable=True),
    sa.Column('rating_shikimori', sa.Float(), nullable=True),
    sa.Column('rating_mangaupdates', sa.Float(), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manga_id')
    )
    op.create_index(op.f('ix_manga_ratings_popularity'), 'manga_ratings', ['popularity'], unique=False)
    op.create_index(op.f('ix_manga_ratings_rating_average'), 'manga_ratings', ['rating_average'], unique=False)
    op.create_table('manga_staff',
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manga_staff_manga', 'manga_staff', ['manga_id'], unique=False)
    op.create_index('ix_manga_staff_person', 'manga_staff', ['person_id'], unique=False)
    op.create_table('manga_tags',
    sa.Column('manga_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manga_id', 'tag_id')
    )
    op.create_index('ix_manga_tag_rank', 'manga_tags', ['rank'], unique=False)
    op.alter_column('chapters', 'groups',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('chapters', 'pages_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'alt_titles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'genres',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'themes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'demographics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'authors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('manga', 'links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('metadata_cache', 'response_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metadata_cache', 'response_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('manga', 'links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'authors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'demographics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'themes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'genres',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('manga', 'alt_titles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chapters', 'pages_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chapters', 'groups',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_manga_tag_rank', table_name='manga_tags')
    op.drop_table('manga_tags')
    op.drop_index('ix_manga_staff_person', table_name='manga_staff')
    op.drop_index('ix_manga_staff_manga', table_name='manga_staff')
    op.drop_table('manga_staff')
    op.drop_index(op.f('ix_manga_ratings_rating_average'), table_name='manga_ratings')
    op.drop_index(op.f('ix_manga_ratings_popularity'), table_name='manga_ratings')
    op.drop_table('manga_ratings')
    op.drop_table('manga_images')
    op.drop_table('manga_genres')
    op.drop_index(op.f('ix_external_links_manga_id'), table_name='external_links')
    op.drop_table('external_links')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('people')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
